"""update product with location

Revision ID: 4626343a01a9
Revises: a779bc9bf133
Create Date: 2025-05-16 11:58:44.381431

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4626343a01a9"
down_revision: Union[str, None] = "a779bc9bf133"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("location_text", sa.String(), nullable=True))
    op.add_column("products", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column("products", sa.Column("longitude", sa.Float(), nullable=True))
    op.add_column("products", sa.Column("location_source", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_products_location_text"), "products", ["location_text"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_location_text"), table_name="products")
    op.drop_column("products", "longitude")
    op.drop_column("products", "latitude")
    op.drop_column("products", "location_text")
    op.drop_column("products", "location_source")
    # ### end Alembic commands ###
