"""create_categories_table

Revision ID: 6ab253f651cc
Revises: e83c393ea211
Create Date: 2025-05-20 20:44:53.066479

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects.postgresql import JSONB
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6ab253f651cc"
down_revision: Union[str, None] = "e83c393ea211"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

PRODUCT_CONDITION_VALUES = ("NEW", "LIKE_NEW", "VERY_GOOD", "GOOD", "FAIR")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"CREATE TYPE product_condition_enum AS ENUM({', '.join(repr(v) for v in PRODUCT_CONDITION_VALUES)})"
    )

    op.add_column(
        "products",
        sa.Column(
            "condition",
            sa.Enum(
                "NEW",
                "LIKE_NEW",
                "VERY_GOOD",
                "GOOD",
                "FAIR",
                name="product_condition_enum",
            ),
            server_default="GOOD",
            nullable=True,
        ),
    )

    op.add_column(
        "products",
        sa.Column(
            "attributes",
            JSONB,
            nullable=True,
        ),
    )

    op.add_column(
        "products",
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default="USD",
            nullable=False,
        ),
    )

    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "category_key", sa.String(), nullable=False
        ),  # unique=True will be added separately or by index
        sa.Column("parent_category_key", sa.String(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("name_en", sa.String(), nullable=False),
        sa.Column("name_he", sa.String(), nullable=True),
        sa.Column("description_ui_en", sa.String(length=100), nullable=True),
        sa.Column("description_ui_he", sa.String(length=100), nullable=True),
        sa.Column("description_for_ai", sa.Text(), nullable=True),
        sa.Column(
            "sort_order", sa.Integer(), server_default=sa.text("0"), nullable=True
        ),  # Added server_default
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=True
        ),  # Added server_default
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "time_updated", sa.DateTime(timezone=True), nullable=True
        ),  # onupdate handled by SQLAlchemy model
        sa.PrimaryKeyConstraint("id"),
        # Explicitly create the UNIQUE constraint on category_key BEFORE the ForeignKey
        # This ensures PostgreSQL knows it can be referenced.
        sa.UniqueConstraint("category_key", name=op.f("uq_categories_category_key")),
    )
    # Create indexes after table creation
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_index(
        op.f("ix_categories_category_key"), "categories", ["category_key"], unique=True
    )  # Ensure index reflects uniqueness
    op.create_index(
        op.f("ix_categories_parent_category_key"),
        "categories",
        ["parent_category_key"],
        unique=False,
    )

    # Now, add the ForeignKey constraint separately, after the table and unique constraint on category_key are defined.
    # This often resolves the "no unique constraint matching given keys" error.
    op.create_foreign_key(
        op.f("fk_categories_parent_category_key_categories"),  # Constraint name
        "categories",  # Source table
        "categories",  # Referenced table
        ["parent_category_key"],  # Local columns
        ["category_key"],  # Remote columns
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "condition")
    op.drop_column("products", "attributes")
    op.drop_column("products", "currency")

    op.execute(f"DROP TYPE product_condition_enum")

    # Drop the foreign key first
    op.drop_constraint(
        op.f("fk_categories_parent_category_key_categories"),
        "categories",
        type_="foreignkey",
    )

    # Drop indexes
    op.drop_index(op.f("ix_categories_parent_category_key"), table_name="categories")
    op.drop_index(op.f("ix_categories_category_key"), table_name="categories")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")

    # Drop the table (which will also drop the unique constraint if it was part of create_table)
    op.drop_table("categories")
    # ### end Alembic commands ###
