"""Add user model and update relationships

Revision ID: 6ca7348e2043
Revises: 209122ea2b68
Create Date: 2025-08-10 11:23:10.795240

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ca7348e2043"
down_revision: Union[str, None] = "209122ea2b68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table
    users_table = op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("allowed_to_contact", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True, server_default="true"),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_uid"), "users", ["uid"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)

    # Data migration from products to users
    op.execute(
        """
        INSERT INTO users (uid, full_name, phone_number, allowed_to_contact)
        SELECT DISTINCT ON (seller_id)
            seller_id,
            seller_name,
            seller_phone,
            seller_allowed_to_contact
        FROM products
        WHERE seller_id IS NOT NULL
        ON CONFLICT (uid) DO NOTHING;
    """
    )

    # Data migration from conversations to users
    op.execute(
        """
        INSERT INTO users (uid)
        SELECT DISTINCT buyer_id FROM conversations WHERE buyer_id IS NOT NULL
        ON CONFLICT (uid) DO NOTHING;
    """
    )
    op.execute(
        """
        INSERT INTO users (uid)
        SELECT DISTINCT seller_id FROM conversations WHERE seller_id IS NOT NULL
        ON CONFLICT (uid) DO NOTHING;
    """
    )

    # Update products table
    op.add_column("products", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.execute(
        """
        UPDATE products
        SET owner_id = users.id
        FROM users
        WHERE products.seller_id = users.uid;
    """
    )
    op.alter_column("products", "owner_id", nullable=False)
    op.create_index(
        op.f("ix_products_owner_id"), "products", ["owner_id"], unique=False
    )
    op.drop_index("ix_products_seller_id", table_name="products")
    op.create_foreign_key(
        "fk_products_owner_id_users", "products", "users", ["owner_id"], ["id"]
    )
    op.drop_column("products", "seller_id")
    op.drop_column("products", "seller_name")
    op.drop_column("products", "seller_phone")
    op.drop_column("products", "seller_allowed_to_contact")

    # Update conversations table
    op.execute(
        """
        UPDATE conversations
        SET buyer_id = (SELECT id FROM users WHERE uid = conversations.buyer_id),
            seller_id = (SELECT id FROM users WHERE uid = conversations.seller_id);
    """
    )

    op.alter_column(
        "conversations",
        "buyer_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="buyer_id::integer",
    )
    op.alter_column(
        "conversations",
        "seller_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="seller_id::integer",
    )
    op.create_foreign_key(
        "fk_conversations_buyer_id_users",
        "conversations",
        "users",
        ["buyer_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_conversations_seller_id_users",
        "conversations",
        "users",
        ["seller_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert conversations table
    op.drop_constraint(
        "fk_conversations_buyer_id_users", "conversations", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_conversations_seller_id_users", "conversations", type_="foreignkey"
    )

    op.alter_column(
        "conversations",
        "buyer_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using="buyer_id::text",
    )
    op.alter_column(
        "conversations",
        "seller_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using="seller_id::text",
    )

    op.execute(
        """
        UPDATE conversations
        SET buyer_id = (SELECT uid FROM users WHERE id = conversations.buyer_id::int),
            seller_id = (SELECT uid FROM users WHERE id = conversations.seller_id::int);
    """
    )

    # Revert products table
    op.add_column(
        "products",
        sa.Column(
            "seller_allowed_to_contact",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "products",
        sa.Column("seller_phone", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "products",
        sa.Column("seller_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "products",
        sa.Column("seller_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )

    op.execute(
        """
        UPDATE products
        SET seller_id = users.uid,
            seller_name = users.full_name,
            seller_phone = users.phone_number,
            seller_allowed_to_contact = users.allowed_to_contact
        FROM users
        WHERE products.owner_id = users.id;
    """
    )
    op.alter_column("products", "seller_id", nullable=False)

    op.drop_constraint("fk_products_owner_id_users", "products", type_="foreignkey")
    op.create_index("ix_products_seller_id", "products", ["seller_id"], unique=False)
    op.drop_index(op.f("ix_products_owner_id"), table_name="products")
    op.drop_column("products", "owner_id")

    # Drop users table
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_uid"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
