"""add_product_status_enum

Revision ID: b6575e29e85d
Revises: 3a27958221e2
Create Date: 2025-05-23 03:57:00.517751

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b6575e29e85d"
down_revision: Union[str, None] = "3a27958221e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PRODUCT_STATUS_VALUES = ("DRAFT", "ACTIVE", "SOLD", "ARCHIVED", "DELETED")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"CREATE TYPE product_status_enum AS ENUM({', '.join(repr(v) for v in PRODUCT_STATUS_VALUES)})"
    )

    op.add_column(
        "products",
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "SOLD",
                "ARCHIVED",
                "DELETED",
                name="product_status_enum",
            ),
            server_default="DRAFT",
            nullable=False,
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "status")
    op.execute(f"DROP TYPE product_status_enum")
    # ### end Alembic commands ###
