"""add_chat_and_negotiation_new

Revision ID: e83c393ea211
Revises: 4626343a01a9
Create Date: 2025-05-18 08:56:30.901394

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e83c393ea211"
down_revision: Union[str, None] = "4626343a01a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "products", sa.Column("min_acceptable_price", sa.Float(), nullable=True)
    )
    op.add_column(
        "products", sa.Column("negotiation_notes_for_ai", sa.Text(), nullable=True)
    )

    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("buyer_id", sa.String(), nullable=False),
        sa.Column("seller_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "last_message_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "closed_deal",
                "closed_no_deal",
                "archived",
                name="conversation_status_enum",
            ),
            server_default="active",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_buyer_id"), "conversations", ["buyer_id"], unique=False
    )
    op.create_index(op.f("ix_conversations_id"), "conversations", ["id"], unique=False)
    op.create_index(
        op.f("ix_conversations_last_message_at"),
        "conversations",
        ["last_message_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversations_product_id"),
        "conversations",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversations_seller_id"), "conversations", ["seller_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversations_status"), "conversations", ["status"], unique=False
    )

    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.String(), nullable=False),
        # Similar consideration for ENUM type for sender_type
        sa.Column(
            "sender_type",
            sa.Enum("buyer", "ai_assistant", "seller", name="message_sender_type_enum"),
            nullable=False,
        ),
        sa.Column("message_text", sa.Text(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_messages_conversation_id"),
        "chat_messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_chat_messages_sender_id"), "chat_messages", ["sender_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_messages_sender_type"),
        "chat_messages",
        ["sender_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_messages_timestamp"), "chat_messages", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_messages_timestamp"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_sender_type"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_sender_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_conversation_id"), table_name="chat_messages")
    op.drop_table("chat_messages")

    op.drop_index(op.f("ix_conversations_status"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_seller_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_product_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_last_message_at"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_buyer_id"), table_name="conversations")
    op.drop_table("conversations")

    op.drop_column("products", "negotiation_notes_for_ai")
    op.drop_column("products", "min_acceptable_price")

    # If you explicitly created ENUM types in upgrade(), you should drop them in downgrade()
    # op.execute("DROP TYPE message_sender_type_enum")
    # op.execute("DROP TYPE conversation_status_enum")
    # ### end Alembic commands ###
